### ISSUE TITLE
Bilder kaputt

### ISSUE THREAD

**Issue by budsbenzer** [jurkov/j-algo-mod#1]
Hallo,

ich habe mir auf Wunsch von Prof. Vogler Deinen Code angesehen. Finde ich super dass Du Dir die Arbeit gemacht hast und vor allem dass Du sie teilst! 

Mir ist beim Diffen mit der Quelle von binaervarianz jedoch aufgefallen, dass die ganzen Bilder im Ordner j-algo/res sich geändert haben und sie nicht mehr richtig dargestellt werden. Es sieht so aus, als wären die Bilder als Textdateien interpretiert worden und alle Unix-Zeilenenden LF in Dos-Zeilenenden CR LF umgewandelt worden.

Beste Grüße
Johannes Osterholzer

**Comment by jurkov** [comment]
Hallo,

ich hab gerade versucht deinen Fehler nachzuvollziehen, bei mir ist keine Änderung an den Dateien vorhanden. Die Vorschau unter Windows und auf github funktioniert z.B. bei https://github.com/jurkov/j-algo-mod/blob/master/res/main/main_pix/aboutHeader.png auch. Für das Bild habe ich den md5-Hash 11912da94e194dacbfa8ccec590f6cd2. Kannst du mir eine genaue Datei nennen? 

Viele Grüße
Christoph

**Comment by budsbenzer** [comment]
Hallo Christoph!

Scheint so dass das Problem nur bei manchen Bildern besteht. Die von Dir genannte Datei hat bei mir den selben Hash.

[Hier](https://gist.github.com/budsbenzer/f7701d978004aea5ffa9) findest Du die Liste der (Bild-)Dateien die bei mir verändert sind. Ganz unten auch die Hashes von einer veränderten Beispieldatei.

Beste Grüße
Johannes

**Comment by jurkov** [comment]
Hallo Johannes,

mit dem Commit https://github.com/jurkov/j-algo-mod/commit/0ec400db89e9cc9ffed50d49ee289dd48cdbfcd2 hab ich hoffentlich alle Bilder erwischt die nicht als Binärdateien hoch geladen waren. Der md5-Hash sollte jetzt passen.

Danke für die Hilfe!

Viele Grüße
Christoph

**Comment by budsbenzer** [comment]
Super, gerne!

Johannes
